import { jsPDF } from "jspdf";
import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";
import type { AxisStat, ScoredJob } from "@engine/engine";

export interface ReportData {
  count: number;
  stability: number;
  likes: AxisStat[];
  dislikes: AxisStat[];
  matches: ScoredJob[];
}

const usd = (n?: number | null) =>
  n == null ? "" : "$" + Math.round(n).toLocaleString("en-US");

const RED: [number, number, number] = [198, 40, 40];

/** Build a one-page PDF of the user's results. Pure client-side. */
function buildPdf(d: ReportData): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 72;

  doc.setFont("helvetica", "bold").setFontSize(26).setTextColor(...RED);
  doc.text("jayobee", M, y);
  doc.setFont("helvetica", "normal").setFontSize(12).setTextColor(90, 90, 90);
  doc.text("Your career preferences", M, y + 20);
  y += 44;

  doc.setFontSize(10).setTextColor(130, 130, 130);
  doc.text(
    `Based on ${d.count} choice${d.count === 1 ? "" : "s"}  ·  ${Math.round(
      d.stability * 100,
    )}% settled`,
    M,
    y,
  );
  y += 12;
  doc.setDrawColor(224, 224, 224).line(M, y, W - M, y);
  y += 30;

  const listSection = (heading: string, items: string[]) => {
    doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(130, 130, 130);
    doc.text(heading.toUpperCase(), M, y);
    y += 18;
    doc.setFont("helvetica", "normal").setFontSize(13).setTextColor(30, 30, 30);
    const text = items.length ? items.join(",  ") : "Not enough signal yet";
    const lines = doc.splitTextToSize(text, W - 2 * M) as string[];
    doc.text(lines, M, y);
    y += lines.length * 17 + 16;
  };

  listSection("You're drawn to", d.likes.map((l) => l.axis));
  listSection("And away from", d.dislikes.map((l) => l.axis));

  doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(130, 130, 130);
  doc.text("CAREERS THAT FIT", M, y);
  y += 20;
  doc.setFontSize(12);
  d.matches.forEach((s, i) => {
    doc.setFont("helvetica", "normal").setTextColor(30, 30, 30);
    doc.text(`${i + 1}.  ${s.job.title}`, M, y);
    const sal = usd(s.job.wage?.median);
    if (sal) {
      doc.setTextColor(130, 130, 130);
      doc.text(sal, W - M, y, { align: "right" });
    }
    y += 18;
  });

  const H = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(160, 160, 160);
  doc.text(
    "Generated by jayobee · your preferences never leave your device",
    M,
    H - 30,
  );

  return doc;
}

/**
 * Generate the PDF and hand it to the OS share sheet (email, Files, etc.). On
 * native we write to the app cache and share the file URI; on web we download.
 * Returns false if the user cancelled, true if shared/saved.
 */
export async function shareResults(d: ReportData): Promise<boolean> {
  const doc = buildPdf(d);
  const fileName = "jayobee-results.pdf";

  if (!Capacitor.isNativePlatform()) {
    doc.save(fileName);
    return true;
  }

  const base64 = doc.output("datauristring").split(",")[1];
  const { uri } = await Filesystem.writeFile({
    path: fileName,
    data: base64,
    directory: Directory.Cache,
  });
  try {
    await Share.share({
      title: "My jayobee results",
      text: "My career preferences from jayobee",
      files: [uri],
      dialogTitle: "Share your results",
    });
    return true;
  } catch {
    // user dismissed the share sheet — not an error
    return false;
  }
}
